### ISSUE TITLE
User Story Ideas

### ISSUE THREAD

**Issue by Dereje1** [chingu-voyage4/Bears-Team-23#3]
- As an authenticated user I will be able to link or upload picture(s) (how many ?) of my pets
-As an authenticated user I will be able to delete pictures I have uploaded
-As an unauthenticated user I will be able to see pictures uploaded by all users
-As an unauthenticated user I will be able to vote on any picture linked/uploaded
-As an unauthenticated user I will be able to view the review score of any picture

**Comment by olddognewtrix123** [comment]
As an unauthenticated user I will be able to create username and password
As an authenticated user I will be able to log on for first time
As an authenticated user I will be able to log on a subsequent time
As an authenticated user I will be able to view my Profile - default values
As an authenticated user I will be able to update my Profile's default values
As an authenticated user I will be able to update my Profile's subsequent values
As an authenticated user I will be able to view all pet profile(s) and cast vote(s)
